# permissions for end users to edit sampleclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleclusterissuer-editor-role
rules:
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleclusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleclusterissuers/status
  verbs:
  - get
