# permissions for end users to view sampleclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleclusterissuer-viewer-role
rules:
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleclusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleclusterissuers/status
  verbs:
  - get
