# permissions for end users to view sampleissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleissuer-viewer-role
rules:
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleissuers/status
  verbs:
  - get
