# permissions for end users to edit sampleissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleissuer-editor-role
rules:
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleissuers/status
  verbs:
  - get
