name: test
on: [pull_request, push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: golang:1.16
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: make test
